# Generated by Django 4.0.5 on 2022-06-16 15:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('subtitle', models.CharField(max_length=30)),
                ('body', models.CharField(max_length=2500)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'diary',
            },
        ),
    ]
